### ISSUE TITLE
Analysis, Requirements and Test ID grids are not showing under traceability page.

### ISSUE THREAD

**Issue by pkmishra-HEC** [mantisbt-plugins/traceability#17]
# Mantis BT version- 2.11.1
[please indicate here the Mantis BT version you use]

# Plugin version-3.0.1
[please indicate here the plugin version you use]

# Description
I have installed and configure Traceability-3.0.1 plugin in MantisBT-2.11.1 as per the instruction provided.
Now when clicking the Traceability menu, error showing as

"Fatal error: Call to undefined function print_bracket_link() in C:\wamp\www\mantisbt-2.11.1\plugins\traceability\pages\api.php on line 97"
I have upload the screenshot.

Please provide the solution for this error.
![traceability issue](https://user-images.githubusercontent.com/37377369/37416392-a2ab37f4-27d3-11e8-850f-f971f5eb5870.jpg)

**Comment by atrol** [comment]
This happens because I removed the function from Mantis Core as it's not used in it since quite a while https://github.com/mantisbt/mantisbt/pull/1259/commits/a123429987c4fe31c082ba2707172a0b93f995a3

I wasn't aware that plugins use this function.
Sorry for the inconvenience, but you have to copy the function to the code of the plugin to fix the issue.

**Comment by pkmishra-HEC** [comment]
Thanks atrol for giving solution of this issue. I have added the required function and now this is working fine. I appreciate for your quick response.

**Comment by rcasteran** [comment]
Reopened to be fixed for Mantis BT 2.11.1 support.

**Comment by rcasteran** [comment]
Verified on MantisBT 2.13.1
